name: Deploy to Production

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  NODE_VERSION: '20.x'

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Create env file
        run: |
          cat > .env.local << 'EOF'
          NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL || 'https://xhzxqxqkmncwbywgqxml.supabase.co' }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhoenFxcXFrbW5jd2J5d2dxeG1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzMyMzc2NzIsImV4cCI6MjA0ODgxMzY3Mn0.dummy' }}
          SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY || 'dummy_service_key' }}
          ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY || 'dummy_anthropic' }}
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY || 'dummy_openai' }}
          EOF
      
      - name: Build Next.js application
        run: |
          npm run build
          echo "Build completed successfully ✅"
      
      - name: Deploy to Vercel
        run: |
          echo "================================================"
          echo "✅ Build successful!"
          echo "================================================"
          echo ""
          echo "Vercel will automatically deploy from GitHub."
          echo "Check your Vercel dashboard for deployment status."
          echo ""
          echo "If Vercel is not set up yet:"
          echo "1. Go to https://vercel.com"
          echo "2. Import this GitHub repository"
          echo "3. It will auto-deploy on every push to main"
          echo "================================================"